// <auto-generated />
using System;
using Ibes.Foundation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ibes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915184901_OrganizacaoInterna")]
    partial class OrganizacaoInterna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ibes.AgendaAtividades.AtividadeAgenda", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtividadeRelacionadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("EntidadePromotoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Intervalo")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Local")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Moeda")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Periodicidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Prazo")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("RecorrenciaAte")
                        .HasColumnType("date");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SerieEncerradaEm")
                        .HasColumnType("date");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TipoAtividadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "AtividadeRelacionadaId");

                    b.HasIndex("IgrejaId", "DataInicio");

                    b.HasIndex("IgrejaId", "EntidadePromotoraId");

                    b.HasIndex("IgrejaId", "ResponsavelId");

                    b.HasIndex("IgrejaId", "TipoAtividadeId");

                    b.ToTable("atividades_agenda", "agenda");
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.EntidadePromotora", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("entidades_promotoras", "agenda");
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.ExcecaoAgenda", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtividadeAgendaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOriginal")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "AtividadeAgendaId", "DataOriginal")
                        .IsUnique();

                    b.ToTable("excecoes_agenda", "agenda");
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.ModeloReuniao", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItensJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("modelos_reuniao", "agenda");
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.TipoAtividade", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("tipos_atividade", "agenda");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.CargoEmbaixada", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "Nome")
                        .IsUnique();

                    b.ToTable("cargos_embaixada", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.Consulado", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("consulados", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.LiderancaConsulado", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsuladoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("MembroConsuladoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoFim")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ConsuladoId")
                        .IsUnique()
                        .HasFilter("\"DataFim\" IS NULL");

                    b.HasIndex("IgrejaId", "MembroConsuladoId");

                    b.HasIndex("IgrejaId", "PessoaId");

                    b.ToTable("liderancas_consulado", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.MandatoDiretoria", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("mandatos_diretoria", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.MembroConsulado", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsuladoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("MotivoFim")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ConsuladoId");

                    b.HasIndex("IgrejaId", "PessoaId")
                        .IsUnique()
                        .HasFilter("\"DataFim\" IS NULL");

                    b.ToTable("membros_consulado", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.OcupacaoCargo", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoEmbaixadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("MandatoDiretoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoFim")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "CargoEmbaixadaId");

                    b.HasIndex("IgrejaId", "MandatoDiretoriaId");

                    b.HasIndex("IgrejaId", "PessoaId");

                    b.ToTable("ocupacoes_cargo", "organizacao");
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.ResultadoEleicao", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoEmbaixadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("MandatoDiretoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OcupacaoCargoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaEscolhidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "CargoEmbaixadaId");

                    b.HasIndex("IgrejaId", "MandatoDiretoriaId");

                    b.HasIndex("IgrejaId", "OcupacaoCargoId");

                    b.HasIndex("IgrejaId", "PessoaEscolhidaId");

                    b.ToTable("resultados_eleicoes", "organizacao");
                });

            modelBuilder.Entity("Ibes.Embaixadas.Conselheiro", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("IgrejaId", "PessoaId");

                    b.ToTable("conselheiros", "embaixadas");
                });

            modelBuilder.Entity("Ibes.Embaixadas.LiderancaEmbaixada", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConselheiroId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ConselheiroId");

                    b.ToTable("liderancas_embaixada", "embaixadas");
                });

            modelBuilder.Entity("Ibes.Foundation.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Chave")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId", "CreatedAt");

                    b.ToTable("auditoria", "auditoria");
                });

            modelBuilder.Entity("Ibes.Foundation.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", "identidade");
                });

            modelBuilder.Entity("Ibes.Foundation.Organizacoes.Embaixada", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataFundacao")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Historia")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeUsual")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId");

                    b.ToTable("embaixadas", "organizacoes");
                });

            modelBuilder.Entity("Ibes.Foundation.Organizacoes.Igreja", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pastor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId");

                    b.ToTable("igrejas", "organizacoes");
                });

            modelBuilder.Entity("Ibes.Foundation.Organizacoes.VinculoIgreja", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Permissoes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("IgrejaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("vinculos_igreja", "identidade");
                });

            modelBuilder.Entity("Ibes.Frequencia.AlteracaoFrequencia", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistroFrequenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SituacaoAnterior")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "RegistroFrequenciaId");

                    b.ToTable("alteracoes_frequencia", "frequencia");
                });

            modelBuilder.Entity("Ibes.Frequencia.RegistroFrequencia", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReuniaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "PessoaId");

                    b.HasIndex("IgrejaId", "ReuniaoId", "PessoaId")
                        .IsUnique();

                    b.ToTable("registros_frequencia", "frequencia");
                });

            modelBuilder.Entity("Ibes.Frequencia.Reuniao", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtividadeAgendaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOriginal")
                        .HasColumnType("date");

                    b.Property<Guid?>("ModeloReuniaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoteiroJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VersaoModelo")
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ModeloReuniaoId");

                    b.HasIndex("IgrejaId", "AtividadeAgendaId", "DataOriginal")
                        .IsUnique();

                    b.ToTable("reunioes", "frequencia");
                });

            modelBuilder.Entity("Ibes.Pessoas.FotoPessoa", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "PessoaId")
                        .IsUnique();

                    b.ToTable("fotos_pessoa", "pessoas");
                });

            modelBuilder.Entity("Ibes.Pessoas.Pessoa", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataBatismo")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LocalBatismo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroCarteira")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool?>("PossuiBiblia")
                        .HasColumnType("boolean");

                    b.Property<string>("SituacaoCarteira")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("IgrejaId", "Id");

                    b.ToTable("pessoas", "pessoas");
                });

            modelBuilder.Entity("Ibes.Pessoas.ResponsavelPessoa", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ResponsavelId");

                    b.HasIndex("IgrejaId", "PessoaId", "ResponsavelId", "DataInicio")
                        .IsUnique();

                    b.ToTable("responsaveis_pessoa", "pessoas");
                });

            modelBuilder.Entity("Ibes.Pessoas.VinculoEclesiastico", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("NomeIgreja")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "PessoaId");

                    b.ToTable("vinculos_eclesiasticos", "pessoas");
                });

            modelBuilder.Entity("Ibes.Progressao.CerimoniaReconhecimento", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("JornadaEmbaixadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JornadaPostoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "JornadaEmbaixadorId");

                    b.HasIndex("IgrejaId", "JornadaPostoId");

                    b.ToTable("cerimonias_reconhecimento", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.ConclusaoRequisito", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<Guid>("JornadaEmbaixadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Requisito")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "JornadaEmbaixadorId", "Requisito")
                        .IsUnique();

                    b.ToTable("conclusoes_requisitos", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.ConclusaoTarefa", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<Guid>("JornadaPostoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TarefaManualId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "TarefaManualId");

                    b.HasIndex("IgrejaId", "JornadaPostoId", "TarefaManualId")
                        .IsUnique();

                    b.ToTable("conclusoes_tarefas", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaEmbaixador", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MesesPermanencia")
                        .HasColumnType("integer");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "PessoaId")
                        .IsUnique();

                    b.ToTable("jornadas_embaixador", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaPosto", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConcluidoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataIngresso")
                        .HasColumnType("date");

                    b.Property<Guid>("JornadaEmbaixadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Posto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VersaoManualId")
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "VersaoManualId");

                    b.HasIndex("IgrejaId", "JornadaEmbaixadorId", "Posto")
                        .IsUnique();

                    b.ToTable("jornadas_posto", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.Manual", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Posto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "Posto")
                        .IsUnique();

                    b.ToTable("manuais", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.TarefaManual", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersaoManualId")
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "VersaoManualId", "OrdemExibicao")
                        .IsUnique();

                    b.ToTable("tarefas_manual", "progressao");
                });

            modelBuilder.Entity("Ibes.Progressao.VersaoManual", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ManualId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("IgrejaId", "Id");

                    b.HasIndex("IgrejaId", "ManualId", "Identificacao")
                        .IsUnique();

                    b.ToTable("versoes_manuais", "progressao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("papeis", "identidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("papeis_claims", "identidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_claims", "identidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_logins", "identidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios_papeis", "identidade");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuarios_tokens", "identidade");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.AtividadeAgenda", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.AgendaAtividades.AtividadeAgenda", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "AtividadeRelacionadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ibes.AgendaAtividades.EntidadePromotora", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "EntidadePromotoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ibes.AgendaAtividades.TipoAtividade", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "TipoAtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.EntidadePromotora", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.ExcecaoAgenda", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.AgendaAtividades.AtividadeAgenda", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "AtividadeAgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.ModeloReuniao", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.AgendaAtividades.TipoAtividade", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.CargoEmbaixada", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.Consulado", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.LiderancaConsulado", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.Consulado", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ConsuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.MembroConsulado", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "MembroConsuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.MandatoDiretoria", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.MembroConsulado", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.Consulado", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ConsuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.OcupacaoCargo", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.CargoEmbaixada", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "CargoEmbaixadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.MandatoDiretoria", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "MandatoDiretoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.ConsuladosDiretoria.ResultadoEleicao", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.CargoEmbaixada", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "CargoEmbaixadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.MandatoDiretoria", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "MandatoDiretoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.ConsuladosDiretoria.OcupacaoCargo", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "OcupacaoCargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaEscolhidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Embaixadas.Conselheiro", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Embaixadas.LiderancaEmbaixada", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Embaixadas.Conselheiro", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ConselheiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Foundation.Auditoria.RegistroAuditoria", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Foundation.Organizacoes.Embaixada", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithOne()
                        .HasForeignKey("Ibes.Foundation.Organizacoes.Embaixada", "IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Foundation.Organizacoes.VinculoIgreja", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Frequencia.AlteracaoFrequencia", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Frequencia.RegistroFrequencia", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "RegistroFrequenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Frequencia.RegistroFrequencia", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Frequencia.Reuniao", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ReuniaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Frequencia.Reuniao", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.AgendaAtividades.AtividadeAgenda", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "AtividadeAgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.AgendaAtividades.ModeloReuniao", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ModeloReuniaoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ibes.Pessoas.FotoPessoa", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Pessoas.Pessoa", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Pessoas.ResponsavelPessoa", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Pessoas.VinculoEclesiastico", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.CerimoniaReconhecimento", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.JornadaEmbaixador", null)
                        .WithMany("Cerimonias")
                        .HasForeignKey("IgrejaId", "JornadaEmbaixadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.JornadaPosto", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "JornadaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.ConclusaoRequisito", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.JornadaEmbaixador", null)
                        .WithMany("Requisitos")
                        .HasForeignKey("IgrejaId", "JornadaEmbaixadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.ConclusaoTarefa", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.JornadaPosto", null)
                        .WithMany("Tarefas")
                        .HasForeignKey("IgrejaId", "JornadaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.TarefaManual", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "TarefaManualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaEmbaixador", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaPosto", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.JornadaEmbaixador", null)
                        .WithMany("Postos")
                        .HasForeignKey("IgrejaId", "JornadaEmbaixadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.VersaoManual", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "VersaoManualId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ibes.Progressao.Manual", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.TarefaManual", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.VersaoManual", null)
                        .WithMany("Tarefas")
                        .HasForeignKey("IgrejaId", "VersaoManualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ibes.Progressao.VersaoManual", b =>
                {
                    b.HasOne("Ibes.Foundation.Organizacoes.Igreja", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ibes.Progressao.Manual", null)
                        .WithMany()
                        .HasForeignKey("IgrejaId", "ManualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ibes.Foundation.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaEmbaixador", b =>
                {
                    b.Navigation("Cerimonias");

                    b.Navigation("Postos");

                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("Ibes.Progressao.JornadaPosto", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Ibes.Progressao.VersaoManual", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
